name: Build & Release @ngx-toolset/date-interceptors

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/date-interceptors/**'

jobs:
  call-build-release-workflow:
    name: Call Build & Release workflow
    uses: ./.github/workflows/build_release.yml
    with:
      PACKAGE_NAME: date-interceptors
    secrets: inherit
