name: Build & Release @ngx-toolset/loading-spinner

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/loading-spinner/**'

jobs:
  call-build-release-workflow:
    name: Call Build & Release workflow
    uses: ./.github/workflows/build_release.yml
    with:
      PACKAGE_NAME: loading-spinner
    secrets: inherit
