name: Build & Release @ngx-toolset/template-type-checker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/template-type-checker/**'

jobs:
  call-build-release-workflow:
    name: Call Build & Release workflow
    uses: ./.github/workflows/build_release.yml
    with:
      PACKAGE_NAME: template-type-checker
    secrets: inherit
