name: Build & Release package

on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
      - name: Run unit tests
        run: |
          npm run test:unit:${{ inputs.PACKAGE_NAME }}:no-watch
      - name: Build lib
        run: |
          npx -c 'ng b @ngx-toolset/${{ inputs.PACKAGE_NAME }}'
          # Somehow calling build script via npm run does not work as of now.
          # npm run build:${{ inputs.PACKAGE_NAME }}
      - name: Copy CHANGELOG
        run: |
          cp projects/${{ inputs.PACKAGE_NAME }}/CHANGELOG.md dist/${{ inputs.PACKAGE_NAME }}/CHANGELOG.md
      - name: Copy LICENSE
        run: |
          cp LICENSE dist/${{ inputs.PACKAGE_NAME }}/LICENSE
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.PACKAGE_NAME }}_artifact
          path: dist/${{ inputs.PACKAGE_NAME }}
  pre_release_validation:
    name: Pre-release validation
    runs-on: ubuntu-latest
    needs: build
    outputs:
      version_increased: ${{ steps.check_package_version.outputs.version_increased }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.PACKAGE_NAME }}_artifact
      - name: Check for package version update
        id: check_package_version
        run: |
          localPackageVersion=$( jq -r '.version' package.json )
          echo "Local package version: $localPackageVersion"
          npmSearchResult=$( npm search @ngx-toolset/${{ inputs.PACKAGE_NAME }} )
          if [ $npmSearchResult -eq 'No matches found for "@ngx-toolset/${{ inputs.PACKAGE_NAME }}"' ]; then
            npmPackageVersion="0.0.0"
          else
            npmPackageVersion=$( npm show @ngx-toolset/${{ inputs.PACKAGE_NAME }} version )
          fi
          echo "Latest package version on NPM: $npmPackageVersion"
          if $(dpkg --compare-versions $localPackageVersion gt $npmPackageVersion);
          then
            echo '::set-output name=version_increased::True'
            echo 'Version updated'
          else
            echo '::set-output name=version_increased::False'
            echo 'Version did not update'
          fi
  npm-package:
    name: NPM package
    runs-on: ubuntu-latest
    needs: pre_release_validation
    if: ${{ needs.pre_release_validation.outputs.version_increased == 'True' }}
    environment: NPM
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.PACKAGE_NAME }}_artifact
      - name: Publish package on NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}
          npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github-release:
    name: GitHub release
    runs-on: ubuntu-latest
    needs: npm-package
    if: ${{ needs.pre_release_validation.outputs.version_increased == 'True' }}
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.PACKAGE_NAME }}_artifact
      - name: Get zip archive name
        run: |
          packageVersion=$( jq -r '.version' package.json )
          echo "packageVersion=$packageVersion" >> $GITHUB_ENV
          zipName="${{ inputs.PACKAGE_NAME }}-v${packageVersion}.zip"
          echo "zipName=$zipName" >> $GITHUB_ENV
      - name: Create GitHub release artifact
        run: |
          wget --quiet --method GET -O npmPackageData.json "https://registry.npmjs.org/@ngx-toolset/${{ inputs.PACKAGE_NAME }}/${{ env.packageVersion }}"
          tarballUrl=$( jq -r '.dist.tarball' npmPackageData.json )
          wget --quiet --method GET -O npmPackage.tgz "$tarballUrl"
          mkdir unpackedPackage
          tar -zxvf ./npmPackage.tgz -C ./unpackedPackage
          cd ./unpackedPackage/package
          zip -r "../../${{ env.zipName }}" *
      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: error
          version: ${{ env.packageVersion }}
          path: ./CHANGELOG.md
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.zipName }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
          name: "@ngx-toolset/${{ inputs.PACKAGE_NAME }} - ${{ env.packageVersion }}"
          tag: "@ngx-toolset/${{ inputs.PACKAGE_NAME }}@${{ env.packageVersion }}"
          token: ${{ secrets.GITHUB_TOKEN }}
