name: Build & Publish @ngx-toolset/lazy-dialogs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/lazy-dialogs/**'

jobs:
  call-build-publish-workflow:
    name: Call Build & Publish workflow
    uses: ./.github/workflows/build_publish.yml
    with:
      packageName: lazy-dialogs
