name: Build & Release @ngx-toolset/lazy-dialogs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/lazy-dialogs/**'

jobs:
  call-build-release-workflow:
    name: Call Build & Release workflow
    uses: ./.github/workflows/build_release.yml
    with:
      PACKAGE_NAME: lazy-dialogs
    secrets: inherit
