name: Build & Publish @ngx-toolset/template-type-checker

on:
  push:
    branches:
      - main
    paths:
      - 'projects/template-type-checker/**'

jobs:
  call-build-publish-workflow:
    name: Call Build & Publish workflow
    uses: ./.github/workflows/build_publish.yml
    with:
      packge_name: template-type-checker
