name: Build & Release @ngx-toolset/api-token-interceptor

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/api-token-interceptor/**'
      
jobs:
  call-build-release-workflow:
    name: Call Build & Release workflow
    permissions:
      contents: write, read
    uses: ./.github/workflows/build_release.yml
    with:
      PACKAGE_NAME: api-token-interceptor
    secrets: inherit
