name: PR validation @ngx-toolset/template-type-checker

on:
  pull_request:
    paths:
      - 'projects/template-type-checker/**'

jobs:
  call-pr-validation-workflow:
    name: Call PR validation workflow
    uses: ./.github/workflows/pr_validation.yml
    with:
      PACKAGE_NAME: template-type-checker
