name: PR validation

on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get package version
        run: |
          packageVersion=$( jq -r '.version' projects/${{ inputs.PACKAGE_NAME }}/package.json )
          echo "packageVersion=$packageVersion" >> $GITHUB_ENV
          echo "$packageVersion"
      - name: Validate changelog entry
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: error
          version: ${{ env.packageVersion }}
          path: ./projects/${{ inputs.PACKAGE_NAME }}/CHANGELOG.md
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
      - name: Check code style
        run: |
          npm run lint:${{ inputs.PACKAGE_NAME }}
      - name: Run unit tests
        run: |
          npm run test:unit:${{ inputs.PACKAGE_NAME }}:no-watch
      - name: Build lib
        run: |
          npx -c 'ng b @ngx-toolset/${{ inputs.PACKAGE_NAME }}'
          # Somehow calling build script via npm run does not work as of now.
          # npm run build:${{ inputs.PACKAGE_NAME }}
