name: PR validation

on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check commit authors
        run: |
          dependabotName="dependabot[bot]"
          committerName="web-flow"
          if [ "${{ github.event.pull_request.user.login }}" = "$dependabotName" ];
          then
            echo "$dependabotName was detected as PR creator"
            wget --quiet --method GET -O commits.json "${{ github.event.pull_request._links.commits.href }}"
            committers=$( jq -r  '[.[] | .committer | .login] | unique' commits.json )
            authors=$( jq -r  '[.[] | .author | .login] | unique' commits.json )
            committersLength=$( jq '. | length' <<< "$committers" )
            authorsLength=$( jq '. | length' <<< "$authors" )
            echo "Committer count: $committersLength"
            echo "Author count: $authorsLength"
            if [ $committersLength -gt 1 ] || [ $authorsLength -gt 1 ];
            then
              echo 'There are too many committers and/or authors for a valid PR branch by $dependabotName'
              exit 1
            else
              committer=$( jq -r '.[0]' <<< $committers )
              author=$( jq -r '.[0]' <<< $authors )
              echo "Committer: $committer"
              echo "Author: $author"
              if [ $committer != "$committerName" ] || [ $author != "$dependabotName" ];
              then
                echo 'Committer and/or author do not have a valid value'
                exit 1
              else
                echo 'Committer and author are valid'
                echo "skipVersionValidation=True" >> $GITHUB_ENV
              fi
            fi
          else
            echo "$dependabotName was not detected as PR creator"
            echo "skipVersionValidation=False" >> $GITHUB_ENV
          fi
      - name: Install pysemver
        run: |
          pip3 install semver
      - name: Get latest package version from NPM
        if: ${{ env.skipVersionValidation == 'False' }}
        run: |
          npmSearchResult=$( npm search @ngx-toolset/${{ inputs.PACKAGE_NAME }} )
          if [[ "$npmSearchResult" == 'No matches found for "@ngx-toolset/${{ inputs.PACKAGE_NAME }}"' ]];
          then
            latestNpmPackageVersion="0.0.0"
          else
            latestNpmPackageVersion=$( npm show @ngx-toolset/${{ inputs.PACKAGE_NAME }} version )
          fi
          echo "latestNpmPackageVersion=$latestNpmPackageVersion" >> $GITHUB_ENV
          echo "Current version: $latestNpmPackageVersion"
      - name: Get PR package version
        if: ${{ env.skipVersionValidation == 'False' }}
        working-directory: ./projects/${{ inputs.PACKAGE_NAME }}
        run: |
          prPackageVersion=$( jq -r '.version' package.json )
          echo "prPackageVersion=$prPackageVersion" >> $GITHUB_ENV
          echo "PR version: $prPackageVersion"
      - name: Verify package version change
        if: ${{ env.skipVersionValidation == 'False' }}
        run: |
          semverCompareResult=$( pysemver compare ${{ env.latestNpmPackageVersion }} ${{ env.prPackageVersion }} )
          if [[ $semverCompareResult == -1 ]];
          then
            echo 'Version changed'
          else
            echo 'Version did not change'
            exit 1
          fi
      - name: Validate changelog entry
        if: ${{ env.skipVersionValidation == 'False' }}
        uses: mindsers/changelog-reader-action@master #mindsers/changelog-reader-action@v2
        with:
          validation_level: error
          version: ${{ env.prPackageVersion }}
          path: ./projects/${{ inputs.PACKAGE_NAME }}/CHANGELOG.md
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
      - name: Check code style
        run: |
          npm run lint:${{ inputs.PACKAGE_NAME }}
      - name: Run unit tests
        run: |
          npm run test:unit:${{ inputs.PACKAGE_NAME }}:no-watch
      - name: Build lib
        run: |
          npx -c 'ng b @ngx-toolset/${{ inputs.PACKAGE_NAME }}'
          # Somehow calling build script via npm run does not work as of now.
          # npm run build:${{ inputs.PACKAGE_NAME }}
