name: PR validation @ngx-toolset/date-interceptors

on:
  pull_request:
    branches:
      - main
      
jobs:
  path-filter:
    name: Path filter
    runs-on: ubuntu-latest
    outputs:
      root_changes: ${{ steps.changes.outputs.root }}
      project_changes: ${{ steps.changes.outputs.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for changes in path
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            root:
              - '!(.eslintrc).json'
              - '.gitignore'
              - 'LICENSE'
            project:
              - 'projects/date-interceptors/**'
  call-pr-validation-workflow:
    name: Call PR validation workflow
    permissions:
      contents: read
      pull-requests: read
    needs: path-filter
    if: ${{ needs.path-filter.outputs.root_changes == 'True' || needs.path-filter.outputs.project_changes == 'True' }}
    uses: ./.github/workflows/pr_validation.yml
    with:
      PACKAGE_NAME: date-interceptors
    secrets: inherit
