name: PR validation @ngx-toolset/date-interceptors

on:
  pull_request:
    paths:
      - 'projects/date-interceptors/**'

jobs:
  call-build-release-workflow:
    name: Call PR validation workflow
    uses: ./.github/workflows/pr_validation.yml
    with:
      PACKAGE_NAME: date-interceptors
