name: Run PR Checks

on: [pull_request]

jobs:
  abcdefg:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout main
        uses: actions/checkout@v2.4.0
        with:
          ref: "main"
          path: main