name: PR validation @ngx-toolset/loading-spinner

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      
jobs:
  path-filter:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changes:
              - 'projects/loading-spinner/**'
  call-pr-validation-workflow:
    name: Call PR validation workflow
    needs: path-filter
    if: ${{ needs.path-filter.outputs.changes == 'True' }}
    uses: ./.github/workflows/pr_validation.yml
    with:
      PACKAGE_NAME: loading-spinner
    secrets: inherit
