name: PR validation @ngx-toolset/lazy-dialogs

on:
  pull_request:
    branches:
      - main
      
jobs:
  path-filter:
    name: Path filter
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.lazy-dialogs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for changes in path
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            lazy-dialogs:
              - 'projects/lazy-dialogs/**'
  call-pr-validation-workflow:
    name: Call PR validation workflow
    needs: path-filter
    if: ${{ needs.path-filter.outputs.lazy-dialogs == 'true' }}
    uses: ./.github/workflows/pr_validation.yml
    with:
      PACKAGE_NAME: lazy-dialogs
    secrets: inherit
