name: Run PR Checks

on: [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout main
        uses: actions/checkout@v2.4.0
        with:
          ref: "main"
          path: main

      - name: Checkout PR branch
        uses: actions/checkout@v2.4.0
        with:
          path: pr

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}