name: PR validation @ngx-toolset/api-token-interceptor

on:
  pull_request:
    paths:
      - 'projects/api-token-interceptor/**'

jobs:
  call-pr-validation-workflow:
    name: Call PR validation workflow
    uses: ./.github/workflows/pr_validation.yml
    with:
      PACKAGE_NAME: api-token-interceptor
